#!/bin/bash

watchexec\
  --project-origin .\
  -w "../cli/example-site/admin/themes/neopoligen-v0.1.0/developer-tools/theme_section_builder"\
  --workdir "../cli/example-site/admin/themes/neopoligen-v0.1.0/developer-tools/theme_section_builder"\
  -e rs,neoj,txt\
  ./build_sections.rs
