#!/bin/bash

watchexec\
  --project-origin .\
  -w "../cli/example-site/themes/neopoligen-v0.1.0/developer-tools/span_builder"\
  --workdir "../cli/example-site/themes/neopoligen-v0.1.0/developer-tools/span_builder"\
  -e py,rs,neoj,txt\
  ./build_spans.py
