#!/bin/bash

cd ../cli \
&& cargo build --release --target aarch64-apple-darwin \
&& cd target/aarch64-apple-darwin/release \
&& mv neopoligengine neopoligengine-aarch64-apple-darwin \
&& ./neopoligengine-aarch64-apple-darwin


