#!/bin/bash

watchexec\
  --project-origin .\
  -w "../cli"\
  --workdir "../cli"\
  -c\
  -r\
  -e rs,neo\
  "bash -c 'cd ../cli && cargo build --release --target aarch64-apple-darwin && cd target/aarch64-apple-darwin/release && mv neopoligengine neopoligengine-aarch64-apple-darwin && ./neopoligengine-aarch64-apple-darwin'"

