#!/bin/bash

watchexec\
  --project-origin .\
  -w "../cli/example-site/admin"\
  --workdir "../cli/example-site/admin/themes"\
  -e xsl,js,css,neo,neoj\
  "rsync -av ./neopoligen-v0.1.0 ~/Documents/Neopoligen/alanwsmith.com/admin/themes/"
