#!/bin/bash

# This syncs the theme and template over to the django.alanwsmith.com site
#
watchexec\
  --project-origin .\
  -w "../cli/example-site/"\
  --workdir "../cli/example-site/themes"\
  -e xsl,js,css,neo,neoj\
  "rsync --delete -av ./neopoligen-v0.1.0 ~/Documents/Neopoligen/django.alanwsmith.com/themes/"
