#!/bin/bash

watchexec\
  --project-origin .\
  -w "../cli/docs-site"\
  --workdir "../cli/docs-site"\
  -e xsl,json,js,css,neo,neoj\
  "rsync --delete -av ./ ~/Documents/Neopoligen/neopoligen.github.io/"
