[package]
name = "neopoligen-cli"
version = "0.0.1"
edition = "2021"

[dev-dependencies]
pretty_assertions = "1.4.0"
rstest = "0.18.2"
divan = "0.1.13"


[[bench]]
name = "basic"
harness = false

[dependencies]
Inflector = "0.11.4"
axum = "0.7.4"
chrono = { version = "0.4.31", features = ["serde"] }
fs_extra = "1.3.0"
itertools = "0.12.0"
minijinja = { version = "1.0.12", features = ["loader", "custom_syntax", "json"] }
nom = "7.1.3"
nom-supreme = "0.8.0"
notify = "6.1.1"
notify-debouncer-mini = "0.4.1"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.110"
serde_yaml = "0.9.30"
syntect = "5.1.0"
tokio = { version = "1.35.1", features = ["rt-multi-thread", "macros"] }
toml = "0.8.10"
tower-http = { version = "0.5.1", features = ["fs"] }
tower-livereload = "0.9.1"
tracing = "0.1"
tracing-appender = "0.2.3"
tracing-chrome = "0.7.1"
tracing-subscriber = "0.3.18"
url = "2.5.0"
urlencoding = "2.1.3"
uuid = { version = "1.7.0", features = ["v4"] }
walkdir = "2.4.0"
dirs = "5.0.1"
divan = "0.1.13"

