#!/bin/bash

rm -rf ~/Documents/Neopoligen/cookbook
export NEOENV=dev 

cd cli\
  && cargo build --release\
  && cd target/release\
  && mv neopoligengine neopoligengine-aarch64-apple-darwin

echo "INFO: Finsihed tauri dev run-before-dev"
