#!/bin/bash

rm -rf ~/Documents/Neopoligen/neopoligen-dev-site
export NEOENV=dev 

cd cli\
  && cargo build --release\
  && cd target/release\
  && mv neopoligengine neopoligengine-aarch64-apple-darwin

